---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: tmc-attacher
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata: 
  name: tmc-attacher
rules:
- apiGroups: ["","apiextensions.k8s.io/v1beta1","apiextensions.k8s.io","apps","batch","rbac.authorization.k8s.io","policy","extensionintegrations.clusters.tmc.cloud.vmware.com"]
  resources: ["*"]
  verbs: ["*"]
--- 
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: tmc-attacherrolebinding
subjects:
- kind: ServiceAccount
  name: tmc-attacher 
  namespace: default
roleRef:
  kind: ClusterRole
  name: tmc-attacher
  apiGroup: rbac.authorization.k8s.io
---
apiVersion: batch/v1
kind: Job
metadata:
  name: tmcjob-{{ .Values.cluster_name }}
spec:
  ttlSecondsAfterFinished: 100
  template:
    spec:
      containers:
      - name: tmcjob-{{ .Values.cluster_name }}
        image: eshanks16/tmcattach:v2
        args: 
        - "./tmc.sh" #Script name DO NOT CHANGE
        - {{ .Values.tmctoken }} #TMC CLI Token
        - {{ .Values.cluster_name }} #Cluster Name
        - {{ .Values.group_name }} #TMC Group Name
      serviceAccountName: tmc-attacher
      restartPolicy: Never